# NVIDIA GPU with >= 48 GiB VRAM (L40 / L40S and larger).
SBATCH_PARTITION=gpu
SBATCH_GRES=gpu:1
SBATCH_CONSTRAINT='gpumem.48gib&nvidiagpu'
SBATCH_CPUS=4
SBATCH_MEM="${SBATCH_MEM:-64G}"
SBATCH_TIME=48:00:00
