#!/usr/bin/env python
"""Generate a larger-K RAVEL task config.

One-pole trains K models where pairwise training needs K(K-1)/2 plus an
aggregation rule. Those counts are *equal* at K=3, the largest class count in
the current suite, so the scaling claim cannot be demonstrated on it at all.
This emits a K>=4 RAVEL variant, where the two diverge (K=8: 28 vs 8).

Needs the RAVEL dataset and the study environment, so submit it as a job -- the
login node has neither. Writes configs/tasks/ravel_<attr>_k<K>.yaml.

Choose K from the data, not from a guess: ``--list`` prints how many rows each
class has, and K should be the largest value where every class still has enough
support. The advantage ratio is (K-1)/2, so K=4 gives 1.5x and K=8 gives 3.5x --
but a class starved of rows costs more than the extra ratio buys.

    TRAIN_CMD='python scripts/make_ravel_task.py --attribute Country --list'       bash slurm/submit_train.sh cpu-1x
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from study.data.mib import ATTR_TO_TASK, _ravel_top_values, _slug_class  # noqa: E402

_NL = chr(10)
PAIR_ON = "  pair: true" + _NL
PAIR_OFF = (
    "  # Pairwise training is quadratic here and is the cost being" + _NL
    + "  # argued against; pass --pair to enable it for a parity arm." + _NL
    + "  pair: false" + _NL
)

TEMPLATE = """# Larger-K RAVEL variant, generated by scripts/make_ravel_task.py.
#
# Exists to demonstrate one-pole's scaling: {k} classes need {pairs} pairwise
# models plus an aggregation rule, versus {k} one-pole models with none. At the
# suite's usual K=3 both counts are 3, so the advantage is invisible there.
# This is a scaling ablation, not an independent main-study task. Keep it
# explicitly runnable while excluding it from list_tasks()/TASKS=all.
study_hidden: true
id: {task}
# study/registry.py resolves the data builder by task id, so a generated task
# must name the base it reuses or it is rejected as unknown.
extends: {base}
classes: [{classes}]
data:
  hf_dataset: mib-bench/ravel
  attribute: {attr}
  top_k: {k}
  # extends: pulls in the base task's data block, including its prebuilt
  # local_path CSV -- which was generated at the base top_k and contains only
  # those classes. Leaving it inherited makes the build short-circuit to that
  # file and fail with "No rows for class ...". Null them so the data is built
  # from the hub at this task's own top_k.
  local_path: null
  neutral_path: null
ablations:
{pair_block}  one_pole: true
training:
  source: both
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--attribute", default="Country", choices=sorted(ATTR_TO_TASK))
    parser.add_argument("--top-k", type=int, default=8)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument(
        "--values",
        default=None,
        help=(
            "Comma-separated class values, bypassing the dataset lookup. Use to "
            "generate offline from a previous --list run: writes from inside an "
            "Apptainer job were observed not to persist, so generating locally "
            "and pushing with rsync_to_slurm.sh is the reliable route."
        ),
    )
    parser.add_argument(
        "--pair",
        action="store_true",
        help=(
            "Also train the K(K-1)/2 pairwise models. Use for a parity arm at "
            "small K, where one-pole must be shown to match pairwise. At large "
            "K this is the cost being argued against -- leave it off."
        ),
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help=(
            "Print the class distribution and the model counts per K, then exit "
            "without writing a config. Use this to choose K from the data."
        ),
    )
    args = parser.parse_args()

    if args.list:
        from collections import Counter

        from datasets import load_dataset

        ds = load_dataset("mib-bench/ravel", split="train")
        counts = Counter(
            row[args.attribute] for row in ds if row["attribute"] == args.attribute
        )
        ordered = counts.most_common()
        print(f"{args.attribute}: {len(ordered)} distinct values")
        print()
        print(f"{'#':>3s}  {'value':28s} {'rows':>7s}  {'pairs':>6s} {'poles':>6s} {'ratio':>6s}")
        for i, (value, n) in enumerate(ordered, start=1):
            pairs, poles = i * (i - 1) // 2, i
            ratio = f"{pairs / poles:.1f}x" if i >= 2 else "-"
            print(f"{i:3d}  {str(value)[:28]:28s} {n:7d}  {pairs:6d} {poles:6d} {ratio:>6s}")
        print()
        print(
            "Pick the largest K whose smallest class still has enough rows to "
            "train and evaluate on. Below K=4 one-pole has no model-count "
            "advantage at all."
        )
        return 0

    if args.top_k < 4:
        parser.error(
            f"--top-k {args.top_k} shows nothing: pairwise and one-pole model "
            "counts are equal at K=3 and pairwise is smaller below that. Use >= 4."
        )

    if args.values:
        values = tuple(v.strip() for v in args.values.split(",") if v.strip())
        if len(values) != args.top_k:
            parser.error(
                f"--values has {len(values)} entries but --top-k is {args.top_k}; "
                "they must agree so the config cannot claim more classes than it has"
            )
    else:
        values = _ravel_top_values(args.attribute, top_k=args.top_k)
    classes = [_slug_class(v) for v in values]
    if len(set(classes)) != len(classes):
        raise ValueError(f"slugs collide: {classes}")

    task = f"{ATTR_TO_TASK[args.attribute]}_k{args.top_k}"
    out = args.out or Path(ROOT) / "configs" / "tasks" / f"{task}.yaml"
    out.write_text(
        TEMPLATE.format(
            task=task,
            base=ATTR_TO_TASK[args.attribute],
            attr=args.attribute,
            k=args.top_k,
            pairs=args.top_k * (args.top_k - 1) // 2,
            classes=", ".join(classes),
            pair_block=(
                PAIR_ON if args.pair else PAIR_OFF
            ),
        ),
        encoding="utf-8",
    )
    print(f"values : {list(values)}")
    print(f"classes: {classes}")
    pairs = args.top_k * (args.top_k - 1) // 2
    print(
        f"models : {pairs} pairwise vs {args.top_k} one-pole"
        + ("  (both trained)" if args.pair else "  (one-pole only)")
    )
    print(f"wrote  : {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
