#!/usr/bin/env python
"""Paired statistical comparisons for the paper headline metrics.

The unit passed to Autorank is one complete ``(model, task)`` block and the
populations are method groups.  Analyses are generated by metric crossed with
one-pole/two-pole constructions.  SAE variants enter wherever the requested
metric is structurally defined; they are not excluded merely because SAE is
untargeted.

The default mode is deliberately useful before the full sweep is finished: it
keeps only listwise-complete blocks and labels every result INTERMEDIATE.  Use
``--strict`` for the final paper analysis; strict mode writes coverage
diagnostics but refuses to calculate statistics unless every structurally
comparable core block is complete.

Examples::

  python analysis/method_statistics.py
  python analysis/method_statistics.py --strict
  python analysis/method_statistics.py --source gpt2-small=suite_full2 \
      --source pythia-70m-deduped=suite_full2 --source llama-3.1-8b
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import math
import sys
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from analysis.plot_style import strip_figure_titles  # noqa: E402

from analysis.summary_latex import (  # noqa: E402
    DEFAULT_CROSS_MODEL_SOURCES,
    HIDDEN_MATRIX_TASKS,
    PAPER_TASK_ORDER,
    collect_canonical_group_rows,
)
from analysis.task_specs import group_is_applicable, spec_for_task  # noqa: E402
from analysis.autorank_config import (  # noqa: E402
    BAYESIAN_RANDOM_STATE,
    BAYESIAN_SAMPLES,
    DEFAULT_ROPES,
    bayesian_autorank_kwargs,
)


DEFAULT_OUT = ROOT / "analysis" / "tables" / "autorank"
DEFAULT_RUNS = ROOT / "runs"
MIN_AUTORANK_BLOCKS = 5
METRICS: Tuple[str, ...] = (
    "detection_score",
    "detection_light_score",
    "intervention_score",
)
PANELS: Tuple[str, ...] = ("one_pole", "two_pole")

# These are the headline method groups, not individual checkpoints or
# appendix ablations.  SAE k=1 is presented simply as SAE in headline output.
SAE_REFERENCE_METHODS: Tuple[str, ...] = ("sae:k1",)
CORE_PANEL_METHODS: Dict[str, Tuple[str, ...]] = {
    "one_pole": (
        "gradiend:one_pole",
        "actiend:one_pole",
        "caga:one_pole",
        "agiend:one_pole",
        "cga:one_pole",
        "caa:one_pole",
        "sae:k1",
    ),
    "two_pole": (
        "gradiend:two_pole",
        "actiend:two_pole",
        "caga:two_pole",
        "agiend:two_pole",
        "cga:two_pole",
        "caa:two_pole",
        "sae:k1",
    ),
}

METHOD_DISPLAY: Dict[str, str] = {
    "gradiend:one_pole": "GRADIEND-1p",
    "gradiend:two_pole": "GRADIEND",
    "actiend:one_pole": "ACTIEND-1p",
    "actiend:two_pole": "ACTIEND",
    "sae:k1": "SAE",
    "sae:kstar": "SAE k*",
    "sae_pre:k1": "SAE-pre k=1",
    "sae_pre:kstar": "SAE-pre k*",
    "caa:one_pole": "CAA-1p",
    "caa:two_pole": "CAA",
    "cga:one_pole": "CGA-1p",
    "cga:two_pole": "CGA",
    "caga:one_pole": "CAGA-1p",
    "caga:two_pole": "CAGA",
    "agiend:one_pole": "AGIEND-1p",
    "agiend:two_pole": "AGIEND",
}

HEADLINE_COMPONENTS: Dict[str, Tuple[str, ...]] = {
    "detection_score": (
        "roc_auc_neutral",
        "neutral_specificity",
        "roc_auc_other",
        "class_exclusivity",
    ),
    # Neutral-only detection.  This is deliberately reported as a secondary
    # estimand: it is comparable across one-sided and pairwise tasks, but it
    # does not measure rival-class separation.
    "detection_light_score": (
        "roc_auc_neutral",
        "neutral_specificity",
    ),
    "intervention_score": (
        "causal_signed_effect",
        "causal_signed_effect_weaken",
    ),
}


@dataclass(frozen=True)
class PanelData:
    metric: str
    panel: str
    methods: Tuple[str, ...]
    matrix: pd.DataFrame
    coverage: pd.DataFrame

    @property
    def n_expected(self) -> int:
        if self.coverage.empty:
            return 0
        return int(self.coverage["structurally_comparable"].sum())

    @property
    def n_complete(self) -> int:
        return int(len(self.matrix))


def _is_finite_number(value: Any) -> bool:
    if value is None or isinstance(value, bool):
        return False
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False


def _is_true(value: Any) -> bool:
    return isinstance(value, bool) and value


def _headline_applicable(method: str, spec: Mapping[str, Any], metric: str) -> bool:
    """Apply structural rules to every constituent of a headline metric."""
    return all(
        group_is_applicable(method, spec, metric=component)
        for component in HEADLINE_COMPONENTS[metric]
    )


def _metric_value(record: Optional[Mapping[str, Any]], metric: str) -> Any:
    """Return a stored metric, deriving the neutral-only score when needed."""
    if record is None:
        return None
    if metric != "detection_light_score":
        return record.get(metric)
    auc_neutral = record.get("roc_auc_neutral")
    specificity = record.get("neutral_specificity")
    if not (_is_finite_number(auc_neutral) and _is_finite_number(specificity)):
        return None
    return min(float(auc_neutral), float(specificity))


def parse_sources(values: Optional[Sequence[str]]) -> Tuple[Tuple[str, str], ...]:
    """Parse repeatable ``MODEL[=OUTPUT_SUBDIR]`` command-line values."""
    if not values:
        return DEFAULT_CROSS_MODEL_SOURCES
    parsed: List[Tuple[str, str]] = []
    seen: set[str] = set()
    for raw in values:
        model, separator, subdir = str(raw).partition("=")
        model = model.strip()
        subdir = subdir.strip() if separator else ""
        if not model:
            raise ValueError(f"invalid empty model in --source {raw!r}")
        if model in seen:
            raise ValueError(f"duplicate --source model {model!r}")
        if subdir and (Path(subdir).is_absolute() or ".." in Path(subdir).parts):
            raise ValueError(f"OUTPUT_SUBDIR must be a relative child name: {subdir!r}")
        seen.add(model)
        parsed.append((model, subdir))
    return tuple(parsed)


def load_source_frames(
    runs_root: Path,
    sources: Sequence[Tuple[str, str]],
    *,
    representation_view: str = "best_overall",
) -> Dict[str, pd.DataFrame]:
    return {
        model: collect_canonical_group_rows(
            runs_root,
            model,
            subdir=subdir,
            representation_view=representation_view,
        )
        for model, subdir in sources
    }


def parse_csv_sources(values: Sequence[str]) -> Tuple[Tuple[str, Path], ...]:
    """Parse normalized local summary inputs for the efficient Autorank path."""
    parsed: List[Tuple[str, Path]] = []
    seen: set[str] = set()
    for raw in values:
        model, separator, raw_path = str(raw).partition("=")
        model, raw_path = model.strip(), raw_path.strip()
        if not separator or not model or not raw_path:
            raise ValueError("--csv must be MODEL=PATH_TO_summary_merged.csv")
        if model in seen:
            raise ValueError(f"duplicate --csv model {model!r}")
        path = Path(raw_path)
        if not path.is_file():
            raise ValueError(f"missing --csv input: {path}")
        seen.add(model)
        parsed.append((model, path))
    return tuple(parsed)


def load_csv_frames(csv_sources: Sequence[Tuple[str, Path]]) -> Dict[str, pd.DataFrame]:
    """Load canonical summary rows without reopening any results.json files."""
    frames: Dict[str, pd.DataFrame] = {}
    for model, path in csv_sources:
        frame = pd.read_csv(path)
        frame["model"] = model
        frames[model] = frame
    return frames


def _row_lookup(frame: pd.DataFrame) -> Dict[Tuple[str, str], Mapping[str, Any]]:
    if frame.empty:
        return {}
    required = {"task", "method_group"}
    if not required.issubset(frame.columns):
        return {}
    lookup: Dict[Tuple[str, str], Mapping[str, Any]] = {}
    for record in frame.to_dict(orient="records"):
        key = (str(record["task"]), str(record["method_group"]))
        if key in lookup:
            raise ValueError(f"duplicate canonical result row for task/method {key}")
        lookup[key] = record
    return lookup


def build_panel_data(
    frames: Mapping[str, pd.DataFrame],
    *,
    sources: Sequence[Tuple[str, str]],
    metric: str,
    panel: str,
    tasks: Sequence[str] = PAPER_TASK_ORDER,
    methods: Optional[Sequence[str]] = None,
) -> PanelData:
    """Build a listwise-complete paired matrix and block-level audit table."""
    if metric not in METRICS:
        raise ValueError(f"metric must be one of {METRICS}, got {metric!r}")
    if panel not in PANELS:
        raise ValueError(f"panel must be one of {PANELS}, got {panel!r}")
    selected_methods = tuple(methods or CORE_PANEL_METHODS[panel])
    if len(selected_methods) < 2:
        raise ValueError("at least two methods are required")
    labels = [METHOD_DISPLAY.get(method, method) for method in selected_methods]
    if len(set(labels)) != len(labels):
        raise ValueError(f"Autorank display labels are not unique: {labels}")

    complete_field = {
        "detection_score": "detection_complete",
        "detection_light_score": "detection_complete",
        "intervention_score": "intervention_complete",
    }[metric]
    visible_tasks = [str(task) for task in tasks if str(task) not in HIDDEN_MATRIX_TASKS]
    lookups = {model: _row_lookup(frames.get(model, pd.DataFrame())) for model, _ in sources}
    matrix_rows: List[Dict[str, Any]] = []
    matrix_index: List[Tuple[str, str]] = []
    coverage_rows: List[Dict[str, Any]] = []

    for model, subdir in sources:
        lookup = lookups[model]
        for task in visible_tasks:
            spec = spec_for_task(task, suite="core", model=model)
            applicable = {
                method: _headline_applicable(method, spec, metric)
                for method in selected_methods
            }
            structurally_comparable = all(applicable.values())
            missing: List[str] = []
            incomplete: List[str] = []
            bad_status: List[str] = []
            values: Dict[str, float] = {}

            if structurally_comparable:
                for method in selected_methods:
                    record = lookup.get((task, method))
                    value = _metric_value(record, metric) if record is not None else None
                    if not _is_finite_number(value):
                        missing.append(method)
                        continue
                    if str(record.get("run_status", "")).lower() != "ok":
                        bad_status.append(method)
                        continue
                    if not _is_true(record.get(complete_field)):
                        incomplete.append(method)
                        continue
                    values[method] = float(value)

            complete = structurally_comparable and len(values) == len(selected_methods)
            coverage_rows.append(
                {
                    "metric": metric,
                    "panel": panel,
                    "model": model,
                    "subdir": subdir or None,
                    "task": task,
                    "structurally_comparable": structurally_comparable,
                    "complete": complete,
                    "n_methods": len(selected_methods),
                    "n_available": len(values),
                    "structural_methods": ";".join(
                        method for method, is_applicable in applicable.items() if not is_applicable
                    ),
                    "missing_methods": ";".join(missing),
                    "raw_incomplete_methods": ";".join(incomplete),
                    "non_ok_methods": ";".join(bad_status),
                }
            )
            if complete:
                matrix_index.append((model, task))
                matrix_rows.append(values)

    matrix = pd.DataFrame(matrix_rows, columns=selected_methods)
    matrix.index = pd.MultiIndex.from_tuples(matrix_index, names=["model", "task"])
    coverage = pd.DataFrame(coverage_rows)
    return PanelData(
        metric=metric,
        panel=panel,
        methods=selected_methods,
        matrix=matrix,
        coverage=coverage,
    )


def select_intermediate_panel(
    frames: Mapping[str, pd.DataFrame],
    *,
    sources: Sequence[Tuple[str, str]],
    metric: str,
    panel: str,
    tasks: Sequence[str] = PAPER_TASK_ORDER,
    methods: Optional[Sequence[str]] = None,
    min_blocks: int = MIN_AUTORANK_BLOCKS,
) -> Tuple[PanelData, Tuple[str, ...]]:
    """Select the largest coherent method ranking available during a sweep.

    Selection uses coverage only, never metric values: maximize the number of
    jointly ranked methods first, then the number of common complete blocks.
    The final ``--strict`` path does not call this function and always requires
    the full predeclared core panel.
    """
    requested = tuple(methods or CORE_PANEL_METHODS[panel])
    full = build_panel_data(
        frames,
        sources=sources,
        metric=metric,
        panel=panel,
        tasks=tasks,
        methods=requested,
    )
    if full.n_complete >= min_blocks:
        return full, ()

    for size in range(len(requested) - 1, 1, -1):
        candidates: List[PanelData] = []
        for subset in combinations(requested, size):
            candidate = build_panel_data(
                frames,
                sources=sources,
                metric=metric,
                panel=panel,
                tasks=tasks,
                methods=subset,
            )
            if candidate.n_complete >= min_blocks:
                candidates.append(candidate)
        if candidates:
            chosen = max(candidates, key=lambda candidate: candidate.n_complete)
            excluded = tuple(method for method in requested if method not in chosen.methods)
            return chosen, excluded
    return full, ()


def _capture_call(function: Any, *args: Any, **kwargs: Any) -> str:
    stream = io.StringIO()
    with contextlib.redirect_stdout(stream):
        function(*args, **kwargs)
    return stream.getvalue()


def _safe_float(value: Any) -> Optional[float]:
    return float(value) if _is_finite_number(value) else None


def build_descriptive_leaderboard(panel_data: PanelData) -> pd.DataFrame:
    """Rank methods on every available complete block, even when n < 5."""
    columns = [
        "position",
        "method_group",
        "display_name",
        "mean_rank",
        "mean",
        "median",
        "n_blocks",
    ]
    if panel_data.matrix.empty:
        return pd.DataFrame(columns=columns)
    per_block_ranks = panel_data.matrix.rank(axis=1, ascending=False, method="average")
    leaderboard = pd.DataFrame(
        {
            "method_group": list(panel_data.methods),
            "display_name": [
                METHOD_DISPLAY.get(method, method) for method in panel_data.methods
            ],
            "mean_rank": [float(per_block_ranks[method].mean()) for method in panel_data.methods],
            "mean": [float(panel_data.matrix[method].mean()) for method in panel_data.methods],
            "median": [float(panel_data.matrix[method].median()) for method in panel_data.methods],
            "n_blocks": len(panel_data.matrix),
        }
    )
    leaderboard["position"] = (
        leaderboard["mean_rank"].rank(method="min", ascending=True).astype(int)
    )
    return leaderboard.sort_values(
        ["mean_rank", "median", "method_group"], ascending=[True, False, True]
    ).reindex(columns=columns)


def build_bayesian_outcomes(
    posterior: pd.DataFrame,
    *,
    label_to_method: Mapping[str, str],
    alpha: float,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Convert Autorank's posterior tuples into explicit A-vs-B outcomes.

    An upper-triangle cell stores ``P(row > column), P(ROPE), P(row < column)``
    for a descending metric.  The output never calls an inconclusive comparison
    equal: practical equivalence requires posterior probability >= 1-alpha.
    """
    labels = [str(label) for label in posterior.index]
    decisions = pd.DataFrame("same method", index=labels, columns=labels)
    rows: List[Dict[str, Any]] = []
    threshold = 1.0 - alpha
    for left_index, left in enumerate(labels):
        for right in labels[left_index + 1 :]:
            probabilities = posterior.loc[left, right]
            reversed_cell = False
            if not isinstance(probabilities, tuple):
                probabilities = posterior.loc[right, left]
                reversed_cell = True
            if not isinstance(probabilities, tuple) or len(probabilities) != 3:
                raise ValueError(f"missing Bayesian posterior for {left!r} vs {right!r}")
            p_left_better, p_equivalent, p_right_better = map(float, probabilities)
            if reversed_cell:
                p_left_better, p_right_better = p_right_better, p_left_better

            if p_left_better >= threshold:
                left_decision, right_decision = "better", "worse"
            elif p_equivalent >= threshold:
                left_decision = right_decision = "practically equivalent"
            elif p_right_better >= threshold:
                left_decision, right_decision = "worse", "better"
            else:
                left_decision = right_decision = "inconclusive"
            decisions.loc[left, right] = left_decision
            decisions.loc[right, left] = right_decision
            rows.append(
                {
                    "method_a": label_to_method[left],
                    "method_b": label_to_method[right],
                    "display_a": left,
                    "display_b": right,
                    "p_a_better": p_left_better,
                    "p_practically_equivalent": p_equivalent,
                    "p_b_better": p_right_better,
                    "decision_a_vs_b": left_decision,
                }
            )
    decisions.index.name = "A_vs_B"
    return pd.DataFrame(rows), decisions


def posterior_probability_matrices(posterior: pd.DataFrame) -> Dict[str, pd.DataFrame]:
    """Materialize Autorank's posterior tuples as A-vs-B probability matrices.

    The row method is A and the column method is B throughout.  This makes
    the heatmap directions explicit rather than depending on Autorank's
    upper-triangle storage convention.
    """
    labels = [str(label) for label in posterior.index]
    matrices = {
        "a_better": pd.DataFrame(float("nan"), index=labels, columns=labels),
        "equivalent": pd.DataFrame(float("nan"), index=labels, columns=labels),
        "b_better": pd.DataFrame(float("nan"), index=labels, columns=labels),
    }
    for left in labels:
        for right in labels:
            if left == right:
                continue
            probabilities = posterior.loc[left, right]
            reversed_cell = False
            if not isinstance(probabilities, tuple):
                probabilities = posterior.loc[right, left]
                reversed_cell = True
            if not isinstance(probabilities, tuple) or len(probabilities) != 3:
                raise ValueError(f"missing Bayesian posterior for {left!r} vs {right!r}")
            p_left, p_equal, p_right = map(float, probabilities)
            if reversed_cell:
                p_left, p_right = p_right, p_left
            matrices["a_better"].loc[left, right] = p_left
            matrices["equivalent"].loc[left, right] = p_equal
            matrices["b_better"].loc[left, right] = p_right
    return matrices


def write_bayesian_posterior_maps(
    posterior: pd.DataFrame,
    decisions: pd.DataFrame,
    path: Path,
) -> Path:
    """Write the four Bayesian Autorank posterior/decision heatmaps."""
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.colors import ListedColormap
    from matplotlib.patches import Patch

    probabilities = posterior_probability_matrices(posterior)
    labels = list(probabilities["a_better"].index)
    figure, axes = plt.subplots(2, 2, figsize=(10.4, 9.0), constrained_layout=True)
    probability_specs = (
        ("a_better", r"$P(A > B)$"),
        ("equivalent", r"$P(A = B)$"),
        ("b_better", r"$P(A < B)$"),
    )
    for axis, (key, title) in zip(axes.flat[:3], probability_specs):
        values = probabilities[key].to_numpy(dtype=float)
        image = axis.imshow(values, cmap="Blues", vmin=0.0, vmax=1.0, aspect="equal")
        for row, col in zip(*np.where(np.isfinite(values))):
            value = values[row, col]
            axis.text(col, row, f"{value:.2f}", ha="center", va="center", fontsize=7.5,
                      color="white" if value >= 0.62 else "#0b0b0b")
        axis.set_title(title)
        axis.set_xticks(range(len(labels)), labels, rotation=35, ha="right", fontsize=7.5)
        axis.set_yticks(range(len(labels)), labels, fontsize=7.5)
        axis.set_xlabel("B")
        axis.set_ylabel("A")
        figure.colorbar(image, ax=axis, fraction=0.046, pad=0.04, label="posterior probability")

    decision_axis = axes.flat[3]
    decision_codes = {
        "better": 0,
        "practically equivalent": 1,
        "worse": 2,
        "inconclusive": 3,
        "same method": 4,
    }
    decision_text = {0: ">", 1: "=", 2: "<", 3: "?", 4: ""}
    values = decisions.reindex(index=labels, columns=labels).apply(
        lambda column: column.map(decision_codes)
    ).to_numpy(dtype=float)
    colors = ["#4c78a8", "#b8b8b8", "#f58518", "#ffffff", "#ececec"]
    decision_axis.imshow(values, cmap=ListedColormap(colors), vmin=0, vmax=len(colors) - 1, aspect="equal")
    for row, col in np.ndindex(values.shape):
        code = int(values[row, col])
        decision_axis.text(col, row, decision_text[code], ha="center", va="center", fontsize=9,
                           color="white" if code in {0, 2} else "#0b0b0b")
    decision_axis.set_title("Bayesian decision for A relative to B")
    decision_axis.set_xticks(range(len(labels)), labels, rotation=35, ha="right", fontsize=7.5)
    decision_axis.set_yticks(range(len(labels)), labels, fontsize=7.5)
    decision_axis.set_xlabel("B")
    decision_axis.set_ylabel("A")
    decision_axis.legend(
        handles=[
            Patch(color=colors[0], label="A better"),
            Patch(color=colors[1], label="practically equivalent"),
            Patch(color=colors[2], label="A worse"),
            Patch(color=colors[3], label="inconclusive"),
        ],
        loc="upper center", bbox_to_anchor=(0.5, -0.19), ncol=2,
        frameon=True, fontsize=7.5,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, bbox_inches="tight")
    plt.close(figure)
    return path


def _write_outcome_markdown(
    path: Path,
    *,
    panel_data: PanelData,
    ranks: pd.DataFrame,
    decisions: pd.DataFrame,
    n_expected: int,
    rope: float,
    alpha: float,
    strict: bool,
    excluded_methods: Sequence[str] = (),
) -> None:
    mode = "FINAL STRICT" if strict else "INTERMEDIATE COMPLETE-CASE"
    lines = [
        f"# {panel_data.metric.removesuffix('_score').title()} — "
        f"{panel_data.panel.replace('_', '-')}",
        "",
        f"**{mode}: {len(panel_data.matrix)}/{n_expected} complete `(model, task)` blocks.**",
        "",
        *(
            [
                "Coverage-only interim selection excluded: "
                + ", ".join(METHOD_DISPLAY.get(method, method) for method in excluded_methods)
                + ".",
                "",
            ]
            if excluded_methods
            else []
        ),
        "## Ranking",
        "",
        "Lower mean rank is better.",
        "",
        "| Position | Method | Mean rank | Median |",
        "|---:|---|---:|---:|",
    ]
    for display_name, row in ranks.iterrows():
        lines.append(
            f"| {int(row['position'])} | {display_name} | "
            f"{float(row['meanrank']):.3f} | {float(row['median']):.3f} |"
        )
    lines.extend(
        [
            "",
            "## Bayesian A-vs-B outcome",
            "",
            f"Absolute ROPE: ±{rope:.3f}; decision threshold: {1-alpha:.0%}. "
            "`Practically equivalent` is an affirmative equivalence result; "
            "`inconclusive` is not equality.",
            "",
            "Rows state the outcome of method A relative to column method B.",
            "",
            "| A \\ B | " + " | ".join(str(column) for column in decisions.columns) + " |",
            "|---|" + "---|" * len(decisions.columns),
        ]
    )
    for label, row in decisions.iterrows():
        lines.append(f"| {label} | " + " | ".join(str(value) for value in row) + " |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_descriptive_only_markdown(
    path: Path,
    *,
    panel_data: PanelData,
    leaderboard: pd.DataFrame,
    n_expected: int,
    status: str,
    reason: str,
    strict: bool,
    excluded_methods: Sequence[str] = (),
) -> None:
    mode = "FINAL STRICT" if strict else "INTERMEDIATE COMPLETE-CASE"
    lines = [
        f"# {panel_data.metric.removesuffix('_score').title()} — "
        f"{panel_data.panel.replace('_', '-')}",
        "",
        f"**{mode}: {len(panel_data.matrix)}/{n_expected} complete `(model, task)` blocks.**",
        "",
        *(
            [
                "Coverage-only interim selection excluded: "
                + ", ".join(METHOD_DISPLAY.get(method, method) for method in excluded_methods)
                + ".",
                "",
            ]
            if excluded_methods
            else []
        ),
        f"Inferential status: **{status}**. {reason}",
        "",
        "## Descriptive ranking only",
        "",
        "Lower mean rank is better. This ordering has no pairwise statistical decision yet.",
        "",
        "| Position | Method | Mean rank | Median |",
        "|---:|---|---:|---:|",
    ]
    for row in leaderboard.to_dict(orient="records"):
        lines.append(
            f"| {int(row['position'])} | {row['display_name']} | "
            f"{float(row['mean_rank']):.3f} | {float(row['median']):.3f} |"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def run_autorank_panel(
    panel_data: PanelData,
    out_dir: Path,
    *,
    alpha: float = 0.05,
    strict: bool = False,
    min_blocks: int = MIN_AUTORANK_BLOCKS,
    rope: Optional[float] = None,
    bayesian_samples: int = BAYESIAN_SAMPLES,
    random_state: int = BAYESIAN_RANDOM_STATE,
    requested_methods: Optional[Sequence[str]] = None,
    excluded_methods: Sequence[str] = (),
) -> Dict[str, Any]:
    """Write one panel's inputs, coverage, report, ranks, LaTeX, and CD plot."""
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{panel_data.metric.removesuffix('_score')}_{panel_data.panel}"
    matrix_path = out_dir / f"{stem}_matrix.csv"
    coverage_path = out_dir / f"{stem}_coverage.csv"
    # A shrinking/interrupted sweep must not leave successful-looking results
    # from an older run beside a newly insufficient input matrix.
    for suffix in (
        "report.txt",
        "ranks.csv",
        "pairwise.csv",
        "bayesian_pairwise.csv",
        "bayesian_decisions.csv",
        "bayesian_posterior_maps.pdf",
        "outcome.md",
        "table.tex",
        "critical_difference.pdf",
    ):
        stale = out_dir / f"{stem}_{suffix}"
        if stale.is_file():
            stale.unlink()
    panel_data.matrix.to_csv(matrix_path, float_format="%.8f")
    panel_data.coverage.to_csv(coverage_path, index=False)
    leaderboard = build_descriptive_leaderboard(panel_data)
    leaderboard.to_csv(out_dir / f"{stem}_leaderboard.csv", index=False, float_format="%.8f")

    n_expected = panel_data.n_expected
    n_complete = panel_data.n_complete
    summary: Dict[str, Any] = {
        "metric": panel_data.metric,
        "panel": panel_data.panel,
        "status": "pending",
        "strict": strict,
        "n_methods": len(panel_data.methods),
        "n_requested_methods": len(tuple(requested_methods or panel_data.methods)),
        "excluded_methods": ";".join(excluded_methods),
        "n_expected_blocks": n_expected,
        "n_complete_blocks": n_complete,
        "n_dropped_blocks": n_expected - n_complete,
        "coverage_fraction": n_complete / n_expected if n_expected else 0.0,
        "complete_blocks_by_model": ";".join(
            f"{model}={count}"
            for model, count in panel_data.matrix.groupby(level="model").size().items()
        ),
        "methods": ";".join(panel_data.methods),
        "omnibus": None,
        "posthoc": None,
        "pvalue": None,
        "critical_distance": None,
        "significant": None,
        "rope": DEFAULT_ROPES[panel_data.metric] if rope is None else rope,
        "leader": (
            str(leaderboard.iloc[0]["method_group"]) if not leaderboard.empty else None
        ),
        "error": None,
    }

    if strict and n_complete != n_expected:
        summary["status"] = "incomplete-strict"
        summary["error"] = "strict mode requires every structurally comparable block"
        _write_descriptive_only_markdown(
            out_dir / f"{stem}_outcome.md",
            panel_data=panel_data,
            leaderboard=leaderboard,
            n_expected=n_expected,
            status=summary["status"],
            reason=str(summary["error"]),
            strict=strict,
            excluded_methods=excluded_methods,
        )
        return summary
    if n_complete < min_blocks:
        summary["status"] = "insufficient-blocks"
        summary["error"] = f"Autorank requires at least {min_blocks} complete paired blocks"
        _write_descriptive_only_markdown(
            out_dir / f"{stem}_outcome.md",
            panel_data=panel_data,
            leaderboard=leaderboard,
            n_expected=n_expected,
            status=summary["status"],
            reason=str(summary["error"]),
            strict=strict,
            excluded_methods=excluded_methods,
        )
        return summary

    try:
        from autorank import autorank, create_report, latex_table, plot_stats
        import matplotlib.pyplot as plt

        display_data = panel_data.matrix.rename(columns=METHOD_DISPLAY)
        diagnostics = io.StringIO()
        with contextlib.redirect_stdout(diagnostics):
            result = autorank(
                display_data,
                alpha=alpha,
                order="descending",
                approach="frequentist",
                force_mode="nonparametric",
                verbose=False,
            )
        resolved_rope = DEFAULT_ROPES[panel_data.metric] if rope is None else float(rope)
        with contextlib.redirect_stdout(diagnostics):
            bayesian_result = autorank(
                display_data,
                **bayesian_autorank_kwargs(
                    panel_data.metric,
                    alpha=alpha,
                    rope=resolved_rope,
                    nsamples=bayesian_samples,
                    random_state=random_state,
                ),
            )

        report = _capture_call(create_report, result)
        mode = "FINAL STRICT" if strict else "INTERMEDIATE COMPLETE-CASE"
        if excluded_methods:
            mode += " ADAPTIVE-METHOD-SUBSET"
        report_path = out_dir / f"{stem}_report.txt"
        report_path.write_text(
            f"{mode} ANALYSIS\n"
            f"Metric: {panel_data.metric}; panel: {panel_data.panel}\n"
            f"Complete paired blocks: {n_complete}/{n_expected}\n"
            f"Dropped incomplete blocks: {n_expected - n_complete}\n\n"
            f"{diagnostics.getvalue()}{report}",
            encoding="utf-8",
        )

        latex = _capture_call(
            latex_table,
            result,
            decimal_places=3,
            label=f"tab:autorank-{stem.replace('_', '-')}",
        )
        latex = latex.replace(
            r"\caption{Summary of populations}",
            rf"\caption{{{mode.title()} Autorank "
            rf"{panel_data.metric.removesuffix('_score').title()} "
            rf"comparison ({panel_data.panel.replace('_', '-')} construction; "
            rf"$n={n_complete}$ complete model--task blocks).}}",
        )
        (out_dir / f"{stem}_table.tex").write_text(latex, encoding="utf-8")

        label_to_method = {
            METHOD_DISPLAY.get(method, method): method for method in panel_data.methods
        }
        ranks = result.rankdf.copy()
        ranks.insert(0, "method_group", [label_to_method[str(index)] for index in ranks.index])
        ranks.insert(
            0,
            "position",
            ranks["meanrank"].rank(method="min", ascending=True).astype(int),
        )
        ranks = ranks.sort_values(["meanrank", "median"], ascending=[True, False])
        ranks.index.name = "display_name"
        ranks.to_csv(out_dir / f"{stem}_ranks.csv", float_format="%.8f")

        pairwise_rows: List[Dict[str, Any]] = []
        labels = [str(index) for index in ranks.index]
        for left_index, left in enumerate(labels):
            for right in labels[left_index + 1 :]:
                left_rank = float(ranks.loc[left, "meanrank"])
                right_rank = float(ranks.loc[right, "meanrank"])
                distance = abs(left_rank - right_rank)
                significant = bool(result.cd is not None and distance > float(result.cd))
                better = left if left_rank < right_rank else right
                pairwise_rows.append(
                    {
                        "method_a": label_to_method[left],
                        "method_b": label_to_method[right],
                        "display_a": left,
                        "display_b": right,
                        "mean_rank_a": left_rank,
                        "mean_rank_b": right_rank,
                        "rank_distance": distance,
                        "critical_distance": _safe_float(result.cd),
                        "significant": significant,
                        "better_method": label_to_method[better] if significant else None,
                        "decision": (
                            f"{better} better" if significant else "not distinguishable"
                        ),
                    }
                )
        pd.DataFrame(pairwise_rows).to_csv(
            out_dir / f"{stem}_pairwise.csv", index=False, float_format="%.8f"
        )

        bayesian_pairs, bayesian_decisions = build_bayesian_outcomes(
            bayesian_result.posterior_matrix,
            label_to_method=label_to_method,
            alpha=alpha,
        )
        bayesian_pairs.to_csv(
            out_dir / f"{stem}_bayesian_pairwise.csv",
            index=False,
            float_format="%.8f",
        )
        bayesian_decisions.to_csv(out_dir / f"{stem}_bayesian_decisions.csv")
        write_bayesian_posterior_maps(
            bayesian_result.posterior_matrix,
            bayesian_decisions,
            out_dir / f"{stem}_bayesian_posterior_maps.pdf",
        )
        _write_outcome_markdown(
            out_dir / f"{stem}_outcome.md",
            panel_data=panel_data,
            ranks=ranks,
            decisions=bayesian_decisions,
            n_expected=n_expected,
            rope=resolved_rope,
            alpha=alpha,
            strict=strict,
            excluded_methods=excluded_methods,
        )

        figure, axis = plt.subplots(figsize=(10, 3.2))
        with contextlib.redirect_stdout(io.StringIO()):
            plot_stats(result, allow_insignificant=True, ax=axis)
        axis.set_title(
            f"{panel_data.metric.removesuffix('_score').title()} — "
            f"{panel_data.panel.replace('_', '-')} ({mode.lower()}, n={n_complete})"
        )
        figure.tight_layout()
        strip_figure_titles(figure)
        figure.savefig(out_dir / f"{stem}_critical_difference.pdf", bbox_inches="tight")
        plt.close(figure)

        summary.update(
            {
                "status": (
                    "ok-final"
                    if strict
                    else (
                        "ok-intermediate-adaptive"
                        if excluded_methods
                        else "ok-intermediate"
                    )
                ),
                "omnibus": result.omnibus,
                "posthoc": result.posthoc,
                "pvalue": _safe_float(result.pvalue),
                "critical_distance": _safe_float(result.cd),
                "significant": bool(result.pvalue < alpha),
            }
        )
    except Exception as exc:  # preserve all coverage/input artifacts on failure
        summary["status"] = "analysis-error"
        summary["error"] = f"{type(exc).__name__}: {exc}"
    return summary


def _write_readme(out_dir: Path, summaries: Sequence[Mapping[str, Any]]) -> Path:
    lines = [
        "# Core-sweep method statistics",
        "",
        "Each analysis uses only listwise-complete `(model, task)` blocks. "
        "`ok-intermediate` results are snapshots of the unfinished sweep, not final paper inference.",
        "",
        "| Metric | Construction | Status | Complete / expected | Friedman p |",
        "|---|---|---:|---:|---:|",
    ]
    for row in summaries:
        pvalue = row.get("pvalue")
        ptext = f"{float(pvalue):.4g}" if _is_finite_number(pvalue) else "—"
        lines.append(
            f"| {row['metric']} | {row['panel']} | {row['status']} | "
            f"{row['n_complete_blocks']} / {row['n_expected_blocks']} | {ptext} |"
        )
    lines.extend(
        [
            "",
            "For every panel, `*_coverage.csv` explains exclusions and `*_matrix.csv` "
            "is the exact paired matrix passed to Autorank. Successful panels additionally "
            "have a readable `*_outcome.md`, rank table, frequentist Nemenyi decisions, "
            "Bayesian better/equivalent/worse probabilities, posterior/decision heatmaps, "
            "decision matrix, LaTeX table, report, and critical-difference plot.",
            "",
        ]
    )
    path = out_dir / "README.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def run_all(
    runs_root: Path,
    out_dir: Path,
    *,
    sources: Sequence[Tuple[str, str]] = DEFAULT_CROSS_MODEL_SOURCES,
    metrics: Sequence[str] = METRICS,
    panels: Sequence[str] = PANELS,
    tasks: Sequence[str] = PAPER_TASK_ORDER,
    alpha: float = 0.05,
    strict: bool = False,
    ropes: Mapping[str, float] = DEFAULT_ROPES,
    bayesian_samples: int = BAYESIAN_SAMPLES,
    random_state: int = BAYESIAN_RANDOM_STATE,
    frames: Optional[Mapping[str, pd.DataFrame]] = None,
) -> pd.DataFrame:
    frames = dict(frames) if frames is not None else load_source_frames(runs_root, sources)
    out_dir.mkdir(parents=True, exist_ok=True)
    summaries: List[Dict[str, Any]] = []
    for metric in metrics:
        for panel in panels:
            requested_methods = CORE_PANEL_METHODS[panel]
            full_data = build_panel_data(
                frames,
                sources=sources,
                metric=metric,
                panel=panel,
                tasks=tasks,
                methods=requested_methods,
            )
            if strict:
                data, excluded_methods = full_data, ()
            else:
                data, excluded_methods = select_intermediate_panel(
                    frames,
                    sources=sources,
                    metric=metric,
                    panel=panel,
                    tasks=tasks,
                    methods=requested_methods,
                )
            stem = f"{metric.removesuffix('_score')}_{panel}"
            if excluded_methods:
                full_data.matrix.to_csv(
                    out_dir / f"{stem}_full_core_matrix.csv", float_format="%.8f"
                )
                full_data.coverage.to_csv(
                    out_dir / f"{stem}_full_core_coverage.csv", index=False
                )
            else:
                for suffix in ("full_core_matrix.csv", "full_core_coverage.csv"):
                    stale = out_dir / f"{stem}_{suffix}"
                    if stale.is_file():
                        stale.unlink()
            summaries.append(
                run_autorank_panel(
                    data,
                    out_dir,
                    alpha=alpha,
                    strict=strict,
                    rope=ropes[metric],
                    bayesian_samples=bayesian_samples,
                    random_state=random_state,
                    requested_methods=requested_methods,
                    excluded_methods=excluded_methods,
                )
            )

    summary_frame = pd.DataFrame(summaries)
    summary_frame.to_csv(out_dir / "summary.csv", index=False)
    _write_readme(out_dir, summaries)
    (out_dir / "manifest.json").write_text(
        json.dumps(
            {
                "mode": "strict" if strict else "intermediate-complete-case",
                "sources": [
                    {"model": model, "subdir": subdir or None}
                    for model, subdir in sources
                ],
                "tasks": [task for task in tasks if task not in HIDDEN_MATRIX_TASKS],
                "panels": {
                    panel: list(CORE_PANEL_METHODS[panel]) for panel in panels
                },
                "metrics": list(metrics),
                "alpha": alpha,
                "ropes": dict(ropes),
                "bayesian_samples": bayesian_samples,
                "random_state": random_state,
                "minimum_autorank_blocks": MIN_AUTORANK_BLOCKS,
                "intermediate_selection": (
                    "largest method subset with at least five common complete blocks; "
                    "maximize method count, then block count; coverage only"
                ),
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return summary_frame


def _comma_values(raw: str, allowed: Iterable[str], name: str) -> Tuple[str, ...]:
    values = tuple(value.strip() for value in raw.split(",") if value.strip())
    unknown = sorted(set(values) - set(allowed))
    if unknown:
        raise ValueError(f"unknown {name}: {', '.join(unknown)}")
    return values


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", type=Path, default=DEFAULT_RUNS)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--source",
        action="append",
        default=None,
        metavar="MODEL[=OUTPUT_SUBDIR]",
        help=(
            "Repeat to override sources. Defaults to GPT-2/Pythia suite_full2 "
            "and root Llama/Qwen runs."
        ),
    )
    parser.add_argument(
        "--csv",
        action="append",
        default=None,
        metavar="MODEL=PATH",
        help=(
            "Use compact per-model summary_merged CSVs instead of reopening "
            "results.json. Intended for the normal local headline workflow."
        ),
    )
    parser.add_argument("--metrics", default=",".join(METRICS))
    parser.add_argument("--panels", default=",".join(PANELS))
    parser.add_argument(
        "--tasks",
        default=",".join(task for task in PAPER_TASK_ORDER if task not in HIDDEN_MATRIX_TASKS),
        help="Comma-separated core task identifiers",
    )
    parser.add_argument("--alpha", type=float, default=0.05)
    parser.add_argument("--detection-rope", type=float, default=DEFAULT_ROPES["detection_score"])
    parser.add_argument(
        "--intervention-rope",
        type=float,
        default=DEFAULT_ROPES["intervention_score"],
    )
    parser.add_argument("--bayesian-samples", type=int, default=50_000)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Final mode: refuse inference unless all expected core blocks are complete",
    )
    args = parser.parse_args()

    try:
        if args.source and args.csv:
            raise ValueError("use either --source or --csv, not both")
        csv_sources = parse_csv_sources(args.csv) if args.csv else ()
        sources = (
            tuple((model, "") for model, _path in csv_sources)
            if csv_sources
            else parse_sources(args.source)
        )
        frames = load_csv_frames(csv_sources) if csv_sources else None
        metrics = _comma_values(args.metrics, METRICS, "metrics")
        panels = _comma_values(args.panels, PANELS, "panels")
        tasks = tuple(task.strip() for task in args.tasks.split(",") if task.strip())
        if not 0 < args.alpha < 1:
            raise ValueError("--alpha must be between 0 and 1")
        if args.detection_rope < 0 or args.intervention_rope < 0:
            raise ValueError("ROPE values must be non-negative")
        if args.bayesian_samples < 1_000:
            raise ValueError("--bayesian-samples must be at least 1000")
        summary = run_all(
            args.runs,
            args.out,
            sources=sources,
            metrics=metrics,
            panels=panels,
            tasks=tasks,
            alpha=args.alpha,
            strict=args.strict,
            ropes={
                "detection_score": args.detection_rope,
                # Both detection estimands are expressed on the same bounded
                # score scale, so the user-facing detection ROPE applies to
                # the neutral-only secondary estimand as well.
                "detection_light_score": args.detection_rope,
                "intervention_score": args.intervention_rope,
            },
            bayesian_samples=args.bayesian_samples,
            random_state=args.random_state,
            frames=frames,
        )
    except ValueError as exc:
        parser.error(str(exc))

    print(summary.to_string(index=False))
    print(f"Wrote {args.out}")
    if args.strict and not summary["status"].eq("ok-final").all():
        raise SystemExit(2)


if __name__ == "__main__":
    main()
